version: "3.3"
services:
  jupyter:
    image: jupyter/tensorflow-notebook
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN?err}
    working_dir: /home/jovyan
    ports:
      - ${EXTERNAL_PORT:-8888}:8888
    volumes:
      - "${NOTEBOOK_VOLUME:-work}:/home/jovyan"
      - "${DATA_VOLUME:-data}:/home/jovyan/data"
volumes:
  work:
    external: false
  data:
    external: false
