version: '2.3'

services:
  jupyterhub:
    image: registry.gitlab.com/clarin-eric/docker-jupyterhub:1.2.1
    ports:
      - ${EXTERNAL_PORT:-88}:8000
    container_name: jupyterhub-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - jupyterhub_auth:/srv/jupyterhub/config/users
    environment:
      DOCKER_JUPYTER_CONTAINER: jupyter-notebook
      DOCKER_JUPYTER_IMAGE: ${DOCKER_JUPYTER_IMAGE:-europena-newspapers:latest}
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub
      DATA_VOLUME: ${DATA_VOLUME:-jupyterhub_data}
      SHARED_VOLUME: ${SHARED_VOLUME:-jupyterhub_shared}
      JUPYTER_HUB_CREDENTIALS: ${JUPYTER_HUB_CREDENTIALS:-}
      JUPYTER_HUB_ADMIN_USER=admin: ${JUPYTER_HUB_ADMIN_USER:-admin}

volumes:
  jupyterhub_data:
  jupyterhub_shared:
  jupyterhub_auth:
