version: '2.3'

services:
  jupyterhub:
    image: registry.gitlab.com/twagoo/docker-jupyterhub:1.0.0-alpha2
    ports:
      - ${EXTERNAL_PORT:-88}:8000
    container_name: jupyterhub-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - jupyterhub_auth:/srv/jupyterhub/config/users
    environment:
      DOCKER_JUPYTER_CONTAINER: jupyter-notebook
      DOCKER_JUPYTER_IMAGE: jupyter/tensorflow-notebook
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub
      SHARED_DATA_VOLUME: ${SHARED_DATA_VOLUME:-}
      JUPYTER_HUB_CREDENTIALS: ${JUPYTER_HUB_CREDENTIALS:-}

volumes:
  jupyterhub_data:
  jupyterhub_auth:
